import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { DynamicShoppingCartProvider } from "@/contexts/ShoppingCartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicShoppingCartProvider>
          <Header />
          <main className="pt-4 pb-8 px-4 lg:px-80 flex justify-center lg:justify-normal lg:block">
            {children}
          </main>
        </DynamicShoppingCartProvider>
      </body>
    </html>
  );
}
